[project]
name = "exploit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "cryptography>=44.0.0",
    "httpx>=0.28.0",
    "pyjwt==1.5.0",
]

[tool.pyright]
exclude = [".venv"]
venvPath = "."
venv = ".venv"
